"""Initial migration

Revision ID: 987501dc9bd1
Revises: 
Create Date: 2024-07-28 13:03:16.775381

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '987501dc9bd1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('airport',
    sa.Column('airport_id', sa.Integer(), nullable=False),
    sa.Column('iata_code', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('city', sa.String(length=50), nullable=False),
    sa.Column('country', sa.String(length=50), nullable=False),
    sa.Column('timezone', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('airport_id')
    )
    op.create_table('ticket',
    sa.Column('ticket_id', sa.Integer(), nullable=False),
    sa.Column('flight_id', sa.Integer(), nullable=True),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('notification_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.customer_id'], ),
    sa.ForeignKeyConstraint(['flight_id'], ['flights.flight_id'], ),
    sa.ForeignKeyConstraint(['notification_id'], ['notifications.notification_id'], ),
    sa.PrimaryKeyConstraint('ticket_id')
    )
    op.drop_table('airports')
    with op.batch_alter_table('flights', schema=None) as batch_op:
        batch_op.drop_constraint('flights_arrival_airport_fkey', type_='foreignkey')
        batch_op.drop_constraint('flights_departure_airport_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'airport', ['departure_airport'], ['airport_id'])
        batch_op.create_foreign_key(None, 'airport', ['arrival_airport'], ['airport_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('flights', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('flights_departure_airport_fkey', 'airports', ['departure_airport'], ['airport_id'])
        batch_op.create_foreign_key('flights_arrival_airport_fkey', 'airports', ['arrival_airport'], ['airport_id'])

    op.create_table('airports',
    sa.Column('airport_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('iata_code', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('city', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('country', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('timezone', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('airport_id', name='airports_pkey')
    )
    op.drop_table('ticket')
    op.drop_table('airport')
    # ### end Alembic commands ###
